CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "mobile" varchar(20),
  "password" varchar(255) NOT NULL,
  "enabled" boolean NOT NULL DEFAULT true,
  "account_non_expired" boolean NOT NULL DEFAULT true,
  "account_non_locked" boolean NOT NULL DEFAULT true,
  "credentials_non_expired" boolean NOT NULL DEFAULT true,
  "email_verified" boolean NOT NULL DEFAULT false,
  "mobile_verified" boolean NOT NULL DEFAULT false,
  "referral_code" varchar(50) UNIQUE,
  "last_login_at" timestamp,
  "last_login_ip" varchar(50),
  "deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "roles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "description" varchar(255)
);

CREATE TABLE "user_roles" (
  "user_id" bigint NOT NULL,
  "role_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "user_login_history" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "platform" varchar(20) NOT NULL,
  "device_id" varchar(150),
  "device_name" varchar(150),
  "os_version" varchar(50),
  "app_version" varchar(50),
  "ip_address" varchar(50),
  "user_agent" text,
  "logged_in_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "password_reset_tokens" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "token" varchar(255) UNIQUE NOT NULL,
  "expires_at" timestamp NOT NULL,
  "used" boolean NOT NULL DEFAULT false,
  "used_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "notifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "title" varchar(200) NOT NULL,
  "message" text NOT NULL,
  "type" varchar(50),
  "is_read" boolean NOT NULL DEFAULT false,
  "read_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "subscriptions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "platform" varchar(20) NOT NULL,
  "product_id" varchar(100) NOT NULL,
  "status" varchar(30) NOT NULL,
  "start_at" timestamp,
  "end_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "billing_transactions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "subscription_id" bigint,
  "platform" varchar(20) NOT NULL,
  "provider" varchar(30) NOT NULL,
  "provider_order_id" varchar(150),
  "provider_payment_id" varchar(150),
  "provider_purchase_token" varchar(255),
  "amount" decimal(10,2),
  "currency" varchar(10),
  "status" varchar(30),
  "raw_response" text,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "daily_login_rewards" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "reward_date" date NOT NULL,
  "reward_type" varchar(50),
  "reward_value" int,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "user_referrals" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "referrer_user_id" bigint NOT NULL,
  "referred_user_id" bigint NOT NULL,
  "referral_code" varchar(50),
  "status" varchar(30),
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "referral_rewards" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "referral_id" bigint NOT NULL,
  "reward_type" varchar(50),
  "reward_value" int,
  "issued_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "referral_installs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "referral_code" varchar(50),
  "device_id" varchar(150),
  "platform" varchar(20),
  "app_installed" boolean NOT NULL DEFAULT false,
  "installed_at" timestamp,
  "registered_user_id" bigint,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX ON "user_roles" ("user_id", "role_id");

CREATE UNIQUE INDEX ON "daily_login_rewards" ("user_id", "reward_date");

CREATE UNIQUE INDEX ON "user_referrals" ("referred_user_id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "user_login_history" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "password_reset_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "subscriptions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "billing_transactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "billing_transactions" ADD FOREIGN KEY ("subscription_id") REFERENCES "subscriptions" ("id");

ALTER TABLE "daily_login_rewards" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_referrals" ADD FOREIGN KEY ("referrer_user_id") REFERENCES "users" ("id");

ALTER TABLE "user_referrals" ADD FOREIGN KEY ("referred_user_id") REFERENCES "users" ("id");

ALTER TABLE "referral_rewards" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "referral_rewards" ADD FOREIGN KEY ("referral_id") REFERENCES "user_referrals" ("id");

ALTER TABLE "referral_installs" ADD FOREIGN KEY ("registered_user_id") REFERENCES "users" ("id");
